Update unittest.yml

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -183,7 +183,7 @@ jobs:
           else
                 echo "::set-output name=env_name::qa"
           fi
-          if [ "${{ steps.values.outputs.branch_name }}" = "feature" ]; then
+          if [ "${{ steps.values.outputs.branch_name }}" = "GitHub" ]; then
             echo "::set-output name=env_name::dev"
           fi
           if [ "${{ steps.values.outputs.branch_name }}" = "nightly" ]; then
@@ -396,14 +396,25 @@ jobs:
            interval: 10
            timeout: "1000"
            
+      #- name: Deploy validation
+       # if: "${{ steps.branch_check.outputs.env_name != '' &&  github.event_name != 'pull_request'}}"
+        #run: |
+         # build=$(curl https://emptyservice.${{ steps.branch_check.outputs.env_name }}.aws.avettatech.com/app/v1/version | jq -r '.buildId')
+          #if [ "$build" = "${{inputs.GITHUB_BUILD_NUMBER}}" ]; then
+           #   echo "Deploy validation successful."
+          #else
+           #   echo "Deploy validation failed."
+          #fi 
+          
       - name: Deploy validation
         if: "${{ steps.branch_check.outputs.env_name != '' &&  github.event_name != 'pull_request'}}"
         run: |
-          build=$(curl https://emptyservice.${{ steps.branch_check.outputs.env_name }}.aws.avettatech.com/app/v1/version | jq -r '.buildId')
-          if [ "$build" = "${{inputs.GITHUB_BUILD_NUMBER}}" ]; then
+          #build=$(curl https://emptyservice.${{ steps.branch_check.outputs.env_name }}.aws.avettatech.com/app/v1/version | jq -r '.buildId')
+          #if [ "$build" = "${{inputs.GITHUB_BUILD_NUMBER}}" ]; then
               echo "Deploy validation successful."
-          else
-              echo "Deploy validation failed."
-          fi     
+          #else
+          echo "Deploy validation failed."
+              exit 1
+          #fi     
           
  
